[[GNUMake]]
arch = "aarch64"
git-tree-sha1 = "9a7b1e76a0426111071480b8151e18bbbde980c5"
os = "macos"

    [[GNUMake.download]]
    sha256 = "c8630a3ead0f37062abd2bbde6667bae70d65444f47f37fa8625f943f36d30ff"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.aarch64-apple-darwin.tar.gz"
[[GNUMake]]
arch = "aarch64"
git-tree-sha1 = "b0857985225e7cef104d56f64c7285ea9604eee6"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "7030c133cf768826dcd170878888c2a2a975e932c265da93883950234fab04a5"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.aarch64-linux-gnu.tar.gz"
[[GNUMake]]
arch = "aarch64"
git-tree-sha1 = "b6b88566365b5f88eedac983f8962c3960dab9c4"
libc = "musl"
os = "linux"

    [[GNUMake.download]]
    sha256 = "84d0a0c27f1374aff4272f5cd06410a4aff4fa9a2475397c133655b70460793f"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.aarch64-linux-musl.tar.gz"
[[GNUMake]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a9c17786124fce2a740ccf1efd2d26447beefe3b"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "182d0f9305541b2ab2244bd8185cf4a1bd27d724f18b5ca5d58b9232799cd3ea"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.armv6l-linux-gnueabihf.tar.gz"
[[GNUMake]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6b633c544520f664bf263b8928d3d1462a2a3176"
libc = "musl"
os = "linux"

    [[GNUMake.download]]
    sha256 = "3e3b9fb40bbf412807c3b3926627fa1be7bd94d6bf960c2932eb49c74c8af7bd"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.armv6l-linux-musleabihf.tar.gz"
[[GNUMake]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3f43a440bdc9b04f8e66c126ebf9baf0327b874d"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "69d8554d159bf6bea48939b6fc1dec78e47ef77ec035d158d7913ca185b5aec2"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.armv7l-linux-gnueabihf.tar.gz"
[[GNUMake]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "88ee56153d5c7bb9e368544039b4c0844141f239"
libc = "musl"
os = "linux"

    [[GNUMake.download]]
    sha256 = "7d70a6dfabbeed9dfe101c82bc7affb942684a3f4c65ed41b3bf741c621c16b7"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.armv7l-linux-musleabihf.tar.gz"
[[GNUMake]]
arch = "i686"
git-tree-sha1 = "0b2f058ebb934845e14a866eaf7e62efa7bd77eb"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "3a46a79ef0982df8d362cf0f146a7e62043b6d551569c2189dddd47db97c0b93"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.i686-linux-gnu.tar.gz"
[[GNUMake]]
arch = "i686"
git-tree-sha1 = "996400d9135bc1d1475aa789365767a7d4e9bf9e"
libc = "musl"
os = "linux"

    [[GNUMake.download]]
    sha256 = "057e7b7f76fd79cee89d3a41a2e198aacab5b55369e4f779d9f4998c42d9b5ba"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.i686-linux-musl.tar.gz"
[[GNUMake]]
arch = "i686"
git-tree-sha1 = "70a2227e798bb33971258b0d572c3caa0c822299"
os = "windows"

    [[GNUMake.download]]
    sha256 = "d817876a921d2c54868fd0a1f0d8d61d6d2bc067836d876778a4b4ba8d30af76"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.i686-w64-mingw32.tar.gz"
[[GNUMake]]
arch = "powerpc64le"
git-tree-sha1 = "a6b019185931d55c08c658007ab7e16849bcef34"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "130c5289250face703b9c90d30b262a50ffe8865dc560d194a4a874a002deb63"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.powerpc64le-linux-gnu.tar.gz"
[[GNUMake]]
arch = "x86_64"
git-tree-sha1 = "7a59ff96f3db89008abee7aca9c3ca6a59158bc0"
os = "macos"

    [[GNUMake.download]]
    sha256 = "aaaccac3e8170b76101ff6a6c2ad62d7889257ad9d9ed902f1c3d3b06c7a0857"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.x86_64-apple-darwin.tar.gz"
[[GNUMake]]
arch = "x86_64"
git-tree-sha1 = "6059eee9f489c45f1d5f313a3149c78f58f9091b"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "f2860140922247f125c9028aa5f4a666ea91d0b0349e6324641c823f7bd64d30"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.x86_64-linux-gnu.tar.gz"
[[GNUMake]]
arch = "x86_64"
git-tree-sha1 = "3abc43cbef13edcc903f610f5fe6c2c1a218b359"
libc = "musl"
os = "linux"

    [[GNUMake.download]]
    sha256 = "f0694537889fcd0c2df5d4320b99b35e288ebd6bde78120d92a9cf03d95dca85"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.x86_64-linux-musl.tar.gz"
[[GNUMake]]
arch = "x86_64"
git-tree-sha1 = "f15115c811b317061e2603303be23b3d236d88df"
os = "freebsd"

    [[GNUMake.download]]
    sha256 = "7c9d66919ef346923a4948097239b7ec291c1fa2c1069ac68c614e70ef53b272"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.x86_64-unknown-freebsd.tar.gz"
[[GNUMake]]
arch = "x86_64"
git-tree-sha1 = "7a3454ff270fae2c56e9bd76b24826baa8c8984a"
os = "windows"

    [[GNUMake.download]]
    sha256 = "0b3e1c5a65a8f286c9de3eb66e8e165565d4f0661c4d973e1c5dc87e54397a04"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.0+0/GNUMake.v4.4.0.x86_64-w64-mingw32.tar.gz"
