[[GNUMake]]
arch = "aarch64"
git-tree-sha1 = "40d8aef5e634f8582bd7578365cabf39b198cd2d"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "2322c175fb092b426f9eb6c24ee22d94ffa6759c3d0c260b74d81abd8120122b"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.3.0+1/GNUMake.v4.3.0.aarch64-linux-gnu.tar.gz"
[[GNUMake]]
arch = "aarch64"
git-tree-sha1 = "8876636e7b90f33cb9b2aa65dfd0039bdb2d410a"
libc = "musl"
os = "linux"

    [[GNUMake.download]]
    sha256 = "68871273f63a7f2d04ce999ff4ad8c1d7bd8366380a3598e7926a0e6a84301b6"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.3.0+1/GNUMake.v4.3.0.aarch64-linux-musl.tar.gz"
[[GNUMake]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6c4a1d3f589270e431407144ae125b24a14ababe"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "2bab31e25edb03335919460ee3b23ade282998f5279f970732656598d4061ef7"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.3.0+1/GNUMake.v4.3.0.armv7l-linux-gnueabihf.tar.gz"
[[GNUMake]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "86e7db30260134d0a325493f9aafb9615f51f229"
libc = "musl"
os = "linux"

    [[GNUMake.download]]
    sha256 = "968fc67c5c761c03c8ff24235cff25e8732d17631062f3276fea41e918add4cb"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.3.0+1/GNUMake.v4.3.0.armv7l-linux-musleabihf.tar.gz"
[[GNUMake]]
arch = "i686"
git-tree-sha1 = "88d56f8272a1857af431f1a7e9973ae4cab7ad03"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "27a121a6ecae56bb77f8e5061212a78e0b0147b07460bcd822fa8cb9d0c00c46"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.3.0+1/GNUMake.v4.3.0.i686-linux-gnu.tar.gz"
[[GNUMake]]
arch = "i686"
git-tree-sha1 = "a428e1acb62c878c03edb538fade2ce79eb0fc7a"
libc = "musl"
os = "linux"

    [[GNUMake.download]]
    sha256 = "628894fbe33af14b7d44afb272c8b92ac874dc335f8544028182e48d3f344636"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.3.0+1/GNUMake.v4.3.0.i686-linux-musl.tar.gz"
[[GNUMake]]
arch = "i686"
git-tree-sha1 = "85feb7a3e7e35c97289dedadce38cabf2e9ddd5a"
os = "windows"

    [[GNUMake.download]]
    sha256 = "7cce1e36a0523f456dd69da572d508c43e153ddff575b82f55bf6357c7915f29"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.3.0+1/GNUMake.v4.3.0.i686-w64-mingw32.tar.gz"
[[GNUMake]]
arch = "powerpc64le"
git-tree-sha1 = "c0930184fc5ed3627865d0e7ccd69a28c8a197eb"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "8096d202fe0a0c400b8c0573c4b9e009f2f10d2fa850a3f495340f16e9c42454"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.3.0+1/GNUMake.v4.3.0.powerpc64le-linux-gnu.tar.gz"
[[GNUMake]]
arch = "x86_64"
git-tree-sha1 = "96f19694813ed61708a0e3192f863574dca5d11d"
os = "macos"

    [[GNUMake.download]]
    sha256 = "32f6ce86d586b8ccf22d387a1e9cca5c89488cebb7503e45638e5ec309c5368c"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.3.0+1/GNUMake.v4.3.0.x86_64-apple-darwin.tar.gz"
[[GNUMake]]
arch = "x86_64"
git-tree-sha1 = "3c2f8a9d0bebd973dac9d785fb43da84047336b8"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "fef1f59e56d2d11e6d700ba22d3444b6e583c663d6883fd0a4f63ab8bd280f0f"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.3.0+1/GNUMake.v4.3.0.x86_64-linux-gnu.tar.gz"
[[GNUMake]]
arch = "x86_64"
git-tree-sha1 = "2a6390da4353f59dd4171ef93210ff542ae5fb9d"
libc = "musl"
os = "linux"

    [[GNUMake.download]]
    sha256 = "38d338b5ab22402eff768bf15e757e942a9cb22ec451711d481a44851dd289f7"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.3.0+1/GNUMake.v4.3.0.x86_64-linux-musl.tar.gz"
[[GNUMake]]
arch = "x86_64"
git-tree-sha1 = "918a4e064195acf8becc5acb845a88475b8e38d7"
os = "freebsd"

    [[GNUMake.download]]
    sha256 = "48ca0ebf360486a46ac8de7179081af8c711d210a69b3ae805b747a1da35706a"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.3.0+1/GNUMake.v4.3.0.x86_64-unknown-freebsd.tar.gz"
[[GNUMake]]
arch = "x86_64"
git-tree-sha1 = "47d01491590f02928b7cc5654455d7c8f0edc839"
os = "windows"

    [[GNUMake.download]]
    sha256 = "7b2a90555e8374756cb5fe8d4f3b8486689558de097e33d0058a6920898b0e23"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.3.0+1/GNUMake.v4.3.0.x86_64-w64-mingw32.tar.gz"
