[[GNUMake]]
arch = "aarch64"
git-tree-sha1 = "1910fab4db573e194a3cc68fb662fd2b485de92a"
os = "macos"

    [[GNUMake.download]]
    sha256 = "2bd8f6a7b6902de8ddfd922e0575b800cc1a149ec66f5c4a4208f3b05ddbd258"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.aarch64-apple-darwin.tar.gz"
[[GNUMake]]
arch = "aarch64"
git-tree-sha1 = "e89358fe8d2a9aa9e594ba6cdbdc99a2ccb511f0"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "b916e2fa3aeb751812d9801f7ed38cf096cc0ae26e195f194c688b77ad14a702"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.aarch64-linux-gnu.tar.gz"
[[GNUMake]]
arch = "aarch64"
git-tree-sha1 = "04613cefe8eb0d55af3a01ff31db072e3cc14b7c"
libc = "musl"
os = "linux"

    [[GNUMake.download]]
    sha256 = "d5effce2307e63852391b806abed93fae96c473d5c917e2624e2298c42ee892f"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.aarch64-linux-musl.tar.gz"
[[GNUMake]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f561bd590a6aa932aa3806180d69b93361f04201"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "d8e1fa4072125c3595854d58ae4a8ddea5d41ff4ef598197f0b81384a6728b41"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.armv6l-linux-gnueabihf.tar.gz"
[[GNUMake]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0ac00d0052d88c28a1dba56bea2cafe70ab42c81"
libc = "musl"
os = "linux"

    [[GNUMake.download]]
    sha256 = "92a223764ffc6f8d5a7ad3b6d8b0fa402c908434fbfafc66252d739b4c344444"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.armv6l-linux-musleabihf.tar.gz"
[[GNUMake]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aacecf6e1c9c2f4b45b13c5306e990c84e52486c"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "57e9a80259ab3fc3c2eb80740b74473ec0af8e4b11e1a9de5fb9d8b30e456303"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.armv7l-linux-gnueabihf.tar.gz"
[[GNUMake]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5539235574a3db4920d6b66cb31a935faa072b4f"
libc = "musl"
os = "linux"

    [[GNUMake.download]]
    sha256 = "6599534a6f5864157f475ce9313c0bf286a9beeb6d95ce9a864e4527ce26df17"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.armv7l-linux-musleabihf.tar.gz"
[[GNUMake]]
arch = "i686"
git-tree-sha1 = "f849ed83fab5ec708e02f7c57129007fd7da4182"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "c3b6e91ff6b91f8c4afada128557f54dc5132d7c2e872c3d911e673be04b9fc1"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.i686-linux-gnu.tar.gz"
[[GNUMake]]
arch = "i686"
git-tree-sha1 = "c6a07ae5a1881c6a8a4935bfc7bf3a1e20851b4e"
libc = "musl"
os = "linux"

    [[GNUMake.download]]
    sha256 = "9eecc6fa4d00722e8e5090c9652b000081901225cd8878c11c9fe9583728ec1f"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.i686-linux-musl.tar.gz"
[[GNUMake]]
arch = "i686"
git-tree-sha1 = "255645910c4b55bc49a141e917041d6008dacde6"
os = "windows"

    [[GNUMake.download]]
    sha256 = "7eed9b3ddc4d2cb0ed64f4fbe5c339d5088bc620075e050861e330e789a14bed"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.i686-w64-mingw32.tar.gz"
[[GNUMake]]
arch = "powerpc64le"
git-tree-sha1 = "fb493cac6d83d9273d94318ee010d8db7cc8bca2"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "27f8f3216ee5b498942dbacd1db8012d21402aac276c95f25f60e37ba8e9e84b"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.powerpc64le-linux-gnu.tar.gz"
[[GNUMake]]
arch = "x86_64"
git-tree-sha1 = "cb7408272413098da9d8e0f2c3c799480e9c3cca"
os = "macos"

    [[GNUMake.download]]
    sha256 = "e4c2ad5924b56521d9fd7646abf074d749b38a69a9d66f8918cfc72b58d6c93d"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.x86_64-apple-darwin.tar.gz"
[[GNUMake]]
arch = "x86_64"
git-tree-sha1 = "5a03c6245324bf4d8a4a46b239e5f531db215738"
libc = "glibc"
os = "linux"

    [[GNUMake.download]]
    sha256 = "9cf76de61a9c2d0cccb985310401431e2840d5b2aa7a7ab98020bd4436978474"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.x86_64-linux-gnu.tar.gz"
[[GNUMake]]
arch = "x86_64"
git-tree-sha1 = "0c1bd19c929cfb1e735454e19dbc7a8717600ea3"
libc = "musl"
os = "linux"

    [[GNUMake.download]]
    sha256 = "6695fd42f20d11d31018438b20ab944e61f3908b30d534a6a9612cf4c79dfcd6"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.x86_64-linux-musl.tar.gz"
[[GNUMake]]
arch = "x86_64"
git-tree-sha1 = "140429e8b26ff4e657c234c180440c87d3f0400b"
os = "freebsd"

    [[GNUMake.download]]
    sha256 = "a7ba1f11182fe2ec0e218a32557d318ec680990e21711ad22e4674ecab505c85"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.x86_64-unknown-freebsd.tar.gz"
[[GNUMake]]
arch = "x86_64"
git-tree-sha1 = "d95fc01e254cc5da4bf624c409085fe1625bbb1f"
os = "windows"

    [[GNUMake.download]]
    sha256 = "f16cf0487618136ac90c8523539a38f8f5ebd2b0ebdd657366975d5642334f54"
    url = "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.4.1+0/GNUMake.v4.4.1.x86_64-w64-mingw32.tar.gz"
